[admiral]
items = ["left", "music",
	"center", "clock",
	"right", "battery",
	"volume", 
	"nazi"]

[music]
path = "mewsic"
reload = 1

[clock]
path = "timeanddate"
reload = 1

[battery]
path = "battery"
reload = 60

[volume]
path = "volume"
reload = 1

[left]
path = "echo '%{l}%{B#EA6562}%{F#FFFFFF}'"
static = true

[center]
path = "echo '%{B-}%{c}%{B#223445}%{F#CBCBCB}'"
static = true

[right]
path = "echo '%{r}%{B-}%{B#4580AD}%{F#FFFFFF}'"
static = true

[nazi]
path = "echo '%{B-}'"
static = true
