[admiral]
items = ["left", "music",
	"center", "clock",
	"right", "battery",
	"volume", 
	"nazi"]

[music]
path  = "bash ~/bin/mewsic"
reload = 1

[clock]
path = "bash ~/bin/timeanddate"
reload = 1

[battery]
path = "bash ~/bin/battery"
reload = 60

[volume]
path = "bash ~/bin/volume"
reload = 1

[left]
path = "echo '%{A}%{l}%{B#E09192}%{F#FFFFFF}'"
static = false 

[center]
path = "echo '%{B-}%{c}%{B#405968}%{F#CBCBCB}'"
static = true

[right]
path = "echo '%{r}%{B-}%{B#4693CC}%{F#FFFFFF}'"
static = true

[nazi]
path = "echo '%{B-}'"
static = true
